# syntax=docker/dockerfile:1
FROM golang:1.19 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /client-auth

# Build lightweight (only contains binary and minimal OS) container for 
# production 
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /client-auth /client-auth

USER nonroot:nonroot

CMD ["/client-auth"]
