name: Push into Main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run
        with:
          file: docker-compose.yml
          service: client-auth-test
          command: go test
